config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "starts#landing"
  resources :cars, only: [ :index, :show ] do
    resources :reviews, only: [ :index, :show, :new, :create ]
    resources :favourites, only: [ :create ]
  end
  resources :favourites, only: [ :index, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :reviews
  has_many :favourites
  validates :brand, :model, :fuel, presence: true
  validates :year, presence: true, numericality: { only_integer: true }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
  # validates :car_id, uniqueness: { scope: :owner_id, message: "has already been favourited by you" }
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars
  validates :nickname, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :comment, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [ :show ]
  def index
    @cars = Car.includes(:owner).all
  end

  def show
    @review = Review.new
    @favourite = Favourite.new
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :set_car, only: [ :create ]

  def index
    @favourites = Favourite.all
  end

  def create
    @favourite = Favourite.new
    @favourite.car_id = @car.id

    if @favourite.save
      redirect_to car_path(@car)
    else
      render "cars/show", status: :unprocessable_entity
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    redirect_to favourites_path, status: :see_other
  end

  private
  def set_car
    @car = Car.find(params[:car_id])
  end

  # def favourite_params
  #   params.require(:favourite).permit(:car_id)
  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_car, only: [ :create ]

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    @review.car = @car
    if @review.save
      redirect_to car_path(@car)
    else
      render "cars/show", status: :unprocessable_entity
    end
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/starts_controller.rb
class StartsController < ApplicationController
  def landing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_stars(rating)
    full_star = "★"
    empty_star = "☆"

    full_star * rating + empty_star * (5 - rating)
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/starts_helper.rb
module StartsHelper
end

app/views/cars/index.html.erb
<div class='navbar'>
	<div id='emoji'>
	  <i class="fa-solid fa-road"></i>
	</div>
	<div>
		<%= link_to "Home", cars_path %>
     | 
    <%= link_to "My garage", favourites_path %>
	</div>
</div>

<div class="container">
  <div class="cards-container">
    <h4> The Paddock </h4>
      <% @cars.each do |car| %>
        <div class="car-card">
          <%= link_to car_path(car) do %>
            <%= image_tag car.image_url %>
          <% end %>
          <%= link_to "#{car.brand} #{car.model}", car_path(car), class: "car-link" %>
          <p><%= car.year %> | <%= car.fuel %></p>
          <div class="owner-tag"> <%= car.owner.nickname %> </div>
        </div>
      <% end %>
  </div>
</div>

app/views/cars/show.html.erb
<div class='navbar'>
	<div id='emoji'>
	  <i class="fa-solid fa-road"></i>
	</div>
	<div>
		<%= link_to "Home", cars_path %>
     | 
    <%= link_to "My garage", favourites_path %>
	</div>
</div>

<div class="container">
  <div class="show-container">
    <div> <%= image_tag @car.image_url %> </div>
    
    <div class="btn-favourite">
    <% if @car.favourites.empty? %>
      <%= simple_form_for [@car, @favourite] do |f| %>
        <%= f.submit "Favourite", class: "favourite-button" %>
      <% end%>
    <% else %>  
      <span class="favourited-text">Favourited</span>
    <% end %>
    </div>

    <div class="details">
      <div class="car-data">
        <h4> <%= @car.brand %> </h4>
        <h5> <%= @car.model %> </h5>
        <h6> <%= @car.fuel %> </h6>
        <h6> <%= @car.year %> </h6>
        <p> <%= link_to "Back to Paddock", cars_path %> </p>
      </div>
      
      <div class="new-review">
        <%= simple_form_for [@car, @review] do |f| %>
          <%= f.input :comment %>
          <%= f.input :rating, collection: 0..5 %>
          <%= f.button :submit, class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>

    <div class="all-reviews">
      <% @car.reviews.each do |review| %>
        <p> <%= review.comment %>
         | 
        <%= render_stars(review.rating) %> </p>
      <% end %>
    </div>

  </div>
</div>

app/views/favourites/index.html.erb
<div class='navbar'>
	<div id='emoji'>
	  <i class="fa-solid fa-road"></i>
	</div>
	<div>
		<%= link_to "Home", cars_path %>
     | 
    <%= link_to "My garage", favourites_path %>
	</div>
</div>

<div class="container">
  <div class="fav-container">
    <h4>My garage</h4>
    <% @favourites.each do |favourite| %>
      <div class="fav-card">
        <%#= image_tag favourite.car.image_url %>
        <%= link_to image_tag(favourite.car.image_url), car_path(favourite.car), class: 'fav-image' %>
        <div class="details">
          <div class="fav-info">
            <%= link_to car_path(favourite.car) do %>
              <h6><%= favourite.car.brand %></h6>
              <h6><%= favourite.car.model %></h6>
            <% end %>
            <p><%= favourite.car.year %> | <%= favourite.car.fuel %></p>
          </div>
          <div class="btn-delete">
            <p><%= link_to raw('<i class="fa-solid fa-trash-can"></i>'), favourite_path(favourite),
                  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
          </div>
        </div>
      </div>
    <% end %>
    <p class="back-link"> <%= link_to "Back to cars", cars_path %> </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Awesome Garage" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/starts/landing.html.erb
<div class="landing-container">
  <div class="card-landing">
    <h3>
      <span class="italy-green">E</span><span class="italy-white">nzo</span><span class="italy-red">'s</span>
    </h3>
    <h4>
      <span class="italy-green">Fai bat</span><span class="italy-white">tere i</span><span class="italy-red">l cuore!</span>
    </h4>
    <p> <%= link_to raw('<span class="italy-green">Ge</span><span class="italy-white">t star</span><span class="italy-red">ted</span>'), cars_path, class: 'start-link' %> </p>
  </div>
</div>